### ISSUE TITLE
bug: Default Rom file manager not working ( content not showing)

### ISSUE THREAD

**Issue by Andysam24** [RisingTechOSS/issue_tracker#10]
### Issue type

Feature not working as intended

### Device

Miatoll ( Poco M2 Pro ) 

### risingOS version

risingOS 2.x

### Exact version / Build date

Rising os v5 beta 

### Bug description

Content not loading in default file manager app 

### Steps to reproduce

.

### Relevant log (logcat/build log)

```shell
.
```

### Solution

Replacement 

### Additional context

Solve because I like this Rom 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 4mede** [comment]
I'm having the same issue. I've attached a log in case that's helpful.
[logcat.txt](https://github.com/user-attachments/files/16602744/logcat.txt)
