### ISSUE TITLE
Sometime excessive memory(ram) usage SystemUI Memory leak?

### ISSUE THREAD

**Issue by ghost** [RisingTechOSS/issue_tracker#17]
### Issue type

User interface

### Device

Realme x2 pro(samurai)

### risingOS version

risingOS 2.x

### Exact version / Build date

Rising OS 5.0 final
#1 Tue Aug 20 16:37:28 UTC 2024

### Bug description

Sometime excessive memory(ram) usage
while using device, systemUI experiences a memory leak that eventually fills the entire system ram after several hours of usage, resulting in all background (launcher, live wallpaper, music player, matlog) and sometimes foreground apps being killed until systemUI or system is restarted which fixes the RAM hog issue until it fills up again.

### Steps to reproduce
Step 1. Observe normal system RAM usage in running services
Step 2. Use Phone normally with background apps (eg live wallpaper)
Step 3. Wait until background or foreground apps crash
Step 4. Observe now bloated system RAM usage
Step 5. Restart system UI or entire device to temporarily fix

### Relevant log (logcat/build log)

```shell
Happens randomly so i don't know how grab log about this bug
```

### Screenshots or videos

![Screenshot_20240822-202323_Ortus Launcher](https://github.com/user-attachments/assets/6c8e0991-75d9-4670-93e4-afd181045d5f)
![Screenshot_20240822-202354_Settings](https://github.com/user-attachments/assets/372502ba-90b9-4366-a8a5-68978ee9a49f)

### Solution

Restart system UI back again normal ram usage

### Additional context

.

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by PptO07** [comment]
@minaripenguin 

There is a method to reproduce it
just change color pallets multiple time from wall paper picker
like keep clicking on various color pallets at same time, spam it hard
and then check ram usage from recents
it will be less than 1 gb free ram available

**Comment by QuantumHorizonn** [comment]
@PptO07
Ur correct 💯 
![Screenshot_20240902-020232_Ortus Launcher](https://github.com/user-attachments/assets/973ac7f2-0ce9-464e-b4ed-48380fdcf654)
