### ISSUE TITLE
Personalization App UI Revamp (inspired by AncientOS)

### ISSUE THREAD

**Issue by zingrx** [RisingTechOSS/issue_tracker#18]
### Issue type

User interface

### Device

I used to use AncientOS last year. The devs didn't develop A14 version. Their latest A13 source included a unique Settings/Personalization app, where it allowed for almost changing everything. I've paid to get access to the private repo to build for my own device (Xiaomi 13 - fuxi). Yet, I can share some screenshots to give you a glimpse.

### risingOS version

risingOS 2.x

### Exact version / Build date

5.0-FINAL

### Bug description

Not a bug - a revamp for Personalizations. Check attached screenshots

### Steps to reproduce

N/A

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

[ancient_Screenshots.zip](https://github.com/user-attachments/files/16736471/ancient_Screenshots.zip)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Omar9t5** [comment]
Netflix not working at all 
DRM checked L1 still not working.

**Comment by QuantumHorizonn** [comment]
Shear screen shot
