### ISSUE TITLE
Still have qs panel lag since android 14🥲

### ISSUE THREAD

**Issue by QuantumHorizonn** [RisingTechOSS/issue_tracker#39]
### Issue type

User interface

### Device

Realme x2 pro(samurai)

### risingOS version

risingOS 2.x

### Exact version / Build date

Fri Nov 15 13:23:31 UTC 2024
Rising os 6.0 beta 3

### Bug description

Still have same qs panel lag when media player running or something downloading I don't when it will fix

### Steps to reproduce

just run something in qs panel jittery laggy 

### Relevant log (logcat/build log)

```shell
🥲
```

### Solution

U know

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kde-yyds** [comment]
The same.
On Redmi K60,
RisingOS-6.0-BETA-GAPPS-COMMUNITY-mondrian

**Comment by QuantumHorizonn** [comment]
> The same. QS fling animation is always laggy On Redmi K60, RisingOS-6.0-BETA-GAPPS-COMMUNITY-mondrian

now fixed check tell ur maintainer for new build

**Comment by kde-yyds** [comment]
> > The same. QS fling animation is always laggy On Redmi K60, RisingOS-6.0-BETA-GAPPS-COMMUNITY-mondrian
> 
> now fixed check tell ur maintainer for new build

Thanks for your reply. Btw can you find which commit fixed this?

**Comment by QuantumHorizonn** [comment]
> > > The same. QS fling animation is always laggy On Redmi K60, RisingOS-6.0-BETA-GAPPS-COMMUNITY-mondrian
> > 
> > 
> > now fixed check tell ur maintainer for new build
> 
> Thanks for your reply. Btw can you find which commit fixed this?

Check on risingos stagging

**Comment by kde-yyds** [comment]
> > > > The same. QS fling animation is always laggy On Redmi K60, RisingOS-6.0-BETA-GAPPS-COMMUNITY-mondrian
> > > 
> > > 
> > > now fixed check tell ur maintainer for new build
> > 
> > 
> > Thanks for your reply. Btw can you find which commit fixed this?
> 
> Check on risingos stagging

Thanks. I will check later. And I will build it when I'm free

**Comment by QuantumHorizonn** [comment]
> > > > > The same. QS fling animation is always laggy On Redmi K60, RisingOS-6.0-BETA-GAPPS-COMMUNITY-mondrian
> > > > 
> > > > 
> > > > now fixed check tell ur maintainer for new build
> > > 
> > > 
> > > Thanks for your reply. Btw can you find which commit fixed this?
> > 
> > 
> > Check on risingos stagging
> 
> Thanks. I will check later. And I will build it again when I'm free

https://github.com/RisingOS-staging
