### ISSUE TITLE
bug: Cannot turn off Auto-confirm unlock

### ISSUE THREAD

**Issue by MarGar12** [RisingTechOSS/issue_tracker#56]
### Issue type

Feature not working as intended

### Device

Xiaomi Redmi Note 13 Pro 5G (garnet)

### risingOS version

risingOS 6.x

### Exact version / Build date

6.0/Sat Dec 21 14:35:32 CET 2024

### Bug description

After inputting the password to turn off Auto-confirm unlock, it doesn't turn off Auto-confirm unlock

### Steps to reproduce

Step 1. Go to Settings
Step 2. Go to Security & privacy
Step 3. Go to Device unlock
Step 3.1. Set Screen Lock to pin (if not used yet)
Step 4. Click settings cog beside Screen lock
Step 5. Toggle Auto-confirm unlock and enter pin

### Relevant log (logcat/build log)

```shell
Idk, check the log file attached in Additional context
```

### Screenshots or videos

https://github.com/user-attachments/assets/36055c75-491b-407e-81b4-92cff09dc2f0

### Additional context

[24_12-20-31-16_053.log](https://github.com/user-attachments/files/18239622/24_12-20-31-16_053.log)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by joshuah345** [comment]
This has been fixed in https://github.com/RisingTechOSS/android_frameworks_base_new/commit/e4cb9ca1af9e111137ab045e4f24c0f72e800dd7
